config/routes.rb
Railstocks::Application.routes.draw do
  devise_for :users
  
  root to: "home#index"

  match 'portfolios/:id/details' => 'portfolios#details'

  resources :dashboard
  resources :portfolios

end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  attr_accessible :name, :tickers_attributes
  belongs_to :user
  has_many :tickers
  
  accepts_nested_attributes_for :tickers

  validates_presence_of :user, :name
  validates_uniqueness_of :name, scope: :user_id, message: "Portfolio name already exists"
end

app/models/ticker.rb
class Ticker < ActiveRecord::Base
  attr_accessible :name
  belongs_to :portfolio

  # validates_uniqueness_of :name, :scope => :portfolio_id, message: "Ticker already in portfolio"
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :portfolios
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
    # redirect_to :controller=>'dashboard', :action => 'index'
    redirect_to :controller=>'portfolios', :action => 'index'
    end
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_filter :authenticate_user!

  def index
    @portfolios = Portfolio.find_all_by_user_id(get_user_id)

    respond_to do |format|
      format.html{ render :index }
      format.json{ render json: Portfolio.includes(:tickers)
                                         .find_all_by_user_id(get_user_id)
                                         .as_json(:include => :tickers) }
    end
  end

  def create
    @portfolio = Portfolio.new(params[:portfolio])
    @portfolio.user = User.find_by_id(get_user_id)

    respond_to do |format|
      if @portfolio.save
        format.html  do 
          flash[:notice] = "Success! Your '#{portfolio.name}' portfolio has been created."
          redirect_to(@portfolio)
        end
        format.json  { render :json => @portfolio, :status => :created }
      else 
        format.html do
          flash[:notice] = "Sorry! Your '#{portfolio.name}' portfolio did not save. That portfolio name already exists."
          redirect_to(@portfolio)
        end
        format.json  { render :json => @portfolio, :status => :unprocessable_entity }
      end
    end
  end

  def show
    respond_to do |format|
       format.html
       format.json{ render json: Portfolio.includes(:tickers)
                                          .find_by_id(params[:id])
                                          .as_json(:include => :tickers)}
    end
  end

  def update
    @portfolio = Portfolio.find(params[:id])
    @portfolio.tickers.clear()
    respond_to do |format|
      if @portfolio.update_attributes(params[:portfolio])
        format.html { redirect_to(index,
                      :notice => "Portfolio was successfully updated.") }
        format.json { head :no_content }
      else
        format.html { redirect_to(index,
                      :notice => "Portfolio was NOT updated.") }
        format.json { render :json => @portfolio.errors,
                    :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @portfolio = Portfolio.find(params[:id])
    @portfolio.destroy
    index
  end

  def details 
    symbols = Array.new() #["GOOG", "YHOO", "AAPL"]

    tickers = Ticker.find_all_by_portfolio_id(params[:id])
    tickers.each{ |t| 
      symbols << t.name
    }

    s_data = YahooFinance.get_standard_quotes(symbols)
    e_data = YahooFinance.get_extended_quotes(symbols)

    portfolio_hash = Hash.new()

    symbols.each do |symbol|

      portfolio_hash[symbol] = Hash.new()
      ticker4Client = portfolio_hash[symbol]

      standardQuote = s_data[symbol]
      extendedQuote = e_data[symbol]

      ticker4Client["symbol"] = standardQuote.symbol
      ticker4Client["name"] = standardQuote.name
      ticker4Client["lastTrade"] = standardQuote.lastTrade
      ticker4Client["volume"] = standardQuote.volume
      ticker4Client["marketCap"] = extendedQuote.marketCap
      ticker4Client["dividendYield"] = extendedQuote.dividendYield
      ticker4Client["pricePerSales"] = extendedQuote.pricePerSales
      ticker4Client["peRatio"] = extendedQuote.peRatio
      ticker4Client["pricePerEPSEstimateCurrentYear"] = extendedQuote.pricePerEPSEstimateCurrentYear
      ticker4Client["pricePerEPSEstimateNextYear"] = extendedQuote.pricePerEPSEstimateNextYear
      ticker4Client["pricePerBook"] = extendedQuote.pricePerBook
      ticker4Client["pegRatio"] = extendedQuote.pegRatio
      ticker4Client["shortRatio"] = extendedQuote.shortRatio
      ticker4Client["movingAve50days"] = extendedQuote.movingAve50days
      ticker4Client["movingAve200days"] = extendedQuote.movingAve200days
    end

    respond_to do |format|
       format.json{ render json: portfolio_hash}
    end

  end

  private
   
  def get_user_id
    session["warden.user.user.key"][0][0]
  end
end

app/controllers/tickers_controller.rb
class TickersController < ApplicationController

	def index
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/dashboard/index.html.erb
<!-- ================== Top Navigation Bar ========================== -->

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
          <div class="nav-collapse collapse"></br>
             <ul class="black-bar pull-right">Welcome, <%= link_to current_user.email, dashboard_index_path %>.   Not you?  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>  
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>

<div class="container">

<h3>Welcome <%= current_user.email %>, </br>
	This is your RailStocks dashboard.  Use this page to customize your RailStocks experience.</h3>
</br>
</br>
<h4><a class="btn btn-info" href="/portfolios">Return to RailStocks</a></h4>

</div>

app/views/home/index.html.erb
</br>
<%= link_to "Register", new_user_registration_path %>  or  <%= link_to "Log In", new_user_session_path %>

<div class="homepage">
</br>
<h2>NSS - Part 2, Ruby on Rails </h2> 
<h4>A Stock Portfolio and Research App, by Viraj Parikh</h4>
</br>

<h4> RailStocks is a portfolio management and research tool that enables a user to create a stock portfolio, retrieve important analytical data points (from Yahoo! Finance) for each company, and have important valuation and momentum metrics summarized. </br> </br>
Features to be released in future versions include access to the SEC Edgar database, StockTwits newsfeed, a S&P 500 "heat map" and an investor education page that comprises of a comprehensive reading list of timeless investment classics.</h4>
</br>
<em>Sincere thanks to Alan Huffman, a terrific computer engineer and mentor.</em> 
</br>
</br>
<p>To view RailStocks on Github, click <b><a href="https://github.com/virajparikh/RailStocks">here</a></b>.</p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
</head>

<body>
<div class="container">

<a id="Logo" target="_top" href="/portfolios" ><img src="http://blog.flamingtext.com/blog/2013/06/26/flamingtext_com_1372210935_138590089.png" border="0" alt="RailStocks logo" title="RailStocks logo"></a>

<!-- <h1 id="Logo">RailStocks</h1> -->

<!-- <div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% end %>
  
</div> -->

 
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<!-- 
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> -->
<%= yield %>

  </div>
</body>
</html>

app/views/portfolios/index.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <title>NSS Rails Project: Viraj Parikh's RailStocks App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="Stock portfolio and research tool using Yahoo! Finance data" content="">
    
  </head>
  
  <body>

<!-- ================== Top Navigation Bar ========================== -->

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
          <div class="nav-collapse collapse"></br>
             <ul class="black-bar pull-right">Welcome, <%= link_to current_user.email, dashboard_index_path %>.   Not you?  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>  
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>  <!-- this div is needed to properly align portfolio buttons -->

<!-- ================== Stock Ticker Table ========================== -->

      <h3 id="portfolioNameInHeader"> </h3>
      <!-- Header added by portfolio.js function addStocksToTable -->
      <table id="portfolioAnalysisTable" class="table table-striped tablesorter">
        <thead>
          <tr>
            <th class='ticker'>Ticker</th>
            <th class='companyName'>Company Name</th>
            <th class='price'>Price</th>
            <th class='sharesOut'>Shares Out</th>
            <th class='mktCap'>Market Cap</th>
            <th class='divYield'>Dividend Yield</th>
            <th class='priceSales'>Price/ Sales</th>
            <th class='trailingPE'>Trailing P/E</th>
            <th class='currentPE'>Current P/E</th>
            <th class='forwardPE'>Forward P/E</th>
            <th class='priceBook'>Price/ Book</th>
            <th class='pegRatio'>PEG Ratio</th>
            <th class='shortRatio'>Short Ratio</th>
            <th class='stMomentum'>Short-Term Momentum<sup>1</sup></th>
            <th class='ltMomentum'>Long-Term Momentum<sup>2</sup></th>
          </tr>
        </thead> 

        <tbody id="stockTable">              
        <!-- Table rows & data added by portfolio.js function addStocksToTable -->
        </tbody>
      </table>

<!-- ================== Portfolio List ========================== -->
    </br>

      <!-- <form name="input" action="html_form_action.asp" method="get">
        <input placeholder="Input Ticker" type="text" name="user">
        <input type="submit" value="Submit">
      </form> -->

      <a id="createPortfolioModalBtn" href="#createPortfolioModal" role="button" class="btn btn-success" data-toggle="modal">Create Portfolio</a>

      <h3>Portfolio List</h3>
      <div class="text-center">
         
        <table class="table">
          <!-- <thead>          </thead>  -->
          <tbody id="portfolioList">              
            <!-- Portfolio list added by js function addPortfolioToTable -->
          </tbody>
        </table>
      </div>
      <br/>
      <br/>
      <div>
        <h4>Footnotes:</h4>
        <h5><sup>1</sup> Short-term momentum is determined by comparing the current stock price to the 50-day moving average, and the 50-day moving average to the 200-day moving average.</h5>

        <h5><sup>2</sup> Long-term momentum is determined by comparing <em>only</em> the 50-day moving average to the 200-day moving average.</h5>
      </div>

      <!-- CREATE PORTFOLIO MODAL
      ================================ -->

      <div id="createPortfolioModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        
        <div class="modal-header">
          <button type="button" class="cancelBtn close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Create Your Portfolio<small> Input your stock tickers here</small></h3>
        </div>
        
        <div class="modal-body">
          <form id="createPortfolioForm" class="form-horizontal">
            <div class="control-group">
              <label class="control-label" for="Name">Portfolio:</label>
              <div class="controls">
                <input type="text" id="createPortfolioName" class="stockInputs clearInputs" name="Portfolio Name" placeholder="Portfolio Name (Required)" class="required" minlength="1" required/>
              </div>
            </div>

            <div class="control-group">
              <label class="control-label" for="tickers">Stocks:</label>
              <div class="controls">
                <textarea rows="3" type="text" id="addTickerInput" class="stockInputs clearInputs" name="Tickers" placeholder="Tickers (separated by spaces)" class="required" minlength="1" required/></textarea>
                
              </div>
            </div>
          </form>
        </div>

        <div class="modal-footer">
          <button class="cancelBtn btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
          <button id="createPortfolioBtn" class="btn btn-success" data-dismiss="modal" aria-hidden="true">Add Portfolio</button>
        </div>
      </div>

      <!-- EDIT PORTFOLIO MODAL
      ================================ -->

      <div id="editPortfolioModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
          <button type="button" class="cancelBtn close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Edit Portfolio<small>  Add or Delete your stock tickers here</small></h3>
      </div>
      
      <div class="modal-body">
        <form id="editPortfolioForm" class="form-horizontal">
          <div class="control-group">
            <label class="control-label" for="Name">Portfolio:</label>
              <div class="controls">
                <h4 id="updatePortfolioName" class="stockInputs clearInputs" name="Portfolio Name" ></h4>
              </div>
          </div>

            <div class="control-group">
              <label class="control-label" for="tickers">Stocks:</label>
              <div class="controls">
                <textarea rows="3"  type="text" id="updateTickerInput" class="stockInputs clearInputs" name="Tickers" placeholder="Tickers (separated by spaces)" required></textarea>
              </div>
            </div>
        </form>
      </div>

        <div class="modal-footer">
          <button class="cancelBtn btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
          <button id="submitUpdatePortfolioBtn" class="btn btn-warning" data-dismiss="modal" aria-hidden="true">Update Portfolio</button>
        </div>
      </div>

  </body>

</html>